### ISSUE TITLE
Add a README to allows new contributors

### ISSUE THREAD

**Issue by mcruzdev** [platformoon/platformoon-docs#1]
We are using `mkdocs` and `mkdocs-material` for this documentation and we do not have a tutorial to show how to execute this documentation locally.

**Comment by rohit192ranjan** [comment]
@mcruzdev I want to contribute for this issue. Can you assign this to me?

**Comment by mcruzdev** [comment]
Hi @rohit192ranjan , TY! Surely!

**Comment by mcruzdev** [comment]
This issue was closed by #3
